# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:
  workdir: &workdir
    working_directory: ~/module-source

  persist-workspace: &persist-workspace
    persist_to_workspace:
      root: ~/module-source
      paths:
        - .

  attach-workspace: &attach-workspace
    attach_workspace:
      at: .

jobs:
  install:
    <<: *workdir

    docker:
      - image: circleci/openjdk:8-jdk

    resource_class: large

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: "Install Atlassian SDK"
          command: |
            sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
            wget https://packages.atlassian.com/api/gpg/key/public
            sudo apt-key add public
            sudo apt-get update
            sudo apt-get install atlassian-plugin-sdk

      - run:
          name: "Check Atlassian SDK installation"
          command: |
            atlas-version

      - save_cache:
          paths:
            - ~/.m2
          key: v2-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: "Build artifacts"
          command: |
            atlas-package

      - run:
          name: "Copy artifacts"
          command: |
            mkdir /tmp/artifacts/
            cp /home/circleci/module-source/target/*.jar /tmp/artifacts/

      - store_artifacts:
          path: /tmp/artifacts/

      - *persist-workspace

workflows:
  version: 2
  build:
    jobs:
      - install